---

- name: Check if kubeadm has already run
  stat:
    path: "/var/lib/kubelet/config.yaml"
  register: kubeadm_already_run

# FIXME: remove hard-coding variables
- name: Initialize first master
  when: inventory_hostname == groups['masters']|first and not kubeadm_already_run.stat.exists
  command: |
    kubeadm init --token {{ token }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ master_ip }} \
                 --service-cidr {{ service_cidr }}
  register: kubeadm_init
  retries: 3
  failed_when: kubeadm_init.rc != 0 and "field is immutable" not in kubeadm_init.stderr

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

# FIXME: owner/group not work properly
- name: Copy admin.conf to Home directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true

# https://github.com/kubernetes/kubeadm/issues/139
# https://github.com/flannel-io/flannel/issues/535#issuecomment-276054316
- name: Copy "kube-flannel.yml" to master node
  copy:
    src: "kube-flannel.yml"
    dest: "~/kube-flannel.yml"
    mode: 0644

- name: Install flannel network add-on
  when: kubeadm_init is succeeded and not kubeadm_already_run.stat.exists
  command: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf \
      apply -f ~/kube-flannel.yml

- name: Set static route
  command: |
    ip route add {{ service_cidr }} dev eth1
  ignore_errors: yes

# - name: Deploy kubernetes dashboard into cluster
#   when: kubeadm_init is succeeded and not kubeadm_already_run.stat.exists
#   command: |
#     kubectl --kubeconfig=/etc/kubernetes/admin.conf \
#       apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/recommended.yaml

